/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package propertytycoongame;

import java.util.ArrayList;
import javafx.application.Platform;
import javafx.concurrent.Task;
import javafx.embed.swing.JFXPanel;
import propertytycoongame.Player.Token;

/**
 *
 * @author Hayden
 */
public class GameGUI extends javax.swing.JFrame {

    CentralControl game;
    static GameGUI gui;
    //Dice dice = new Dice();
    Token st;
    Boolean fullGame;
    Boolean running = false;

    /**
     * Creates new form GameGUI
     */
    public GameGUI() {
        initComponents();
        createTokenList();
    }

    /**
     * This method is called from within the constructor to initialise the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buyDialog = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnBack = new javax.swing.JToggleButton();
        btnBuy = new javax.swing.JToggleButton();
        txtName = new javax.swing.JLabel();
        txtPrice = new javax.swing.JLabel();
        playerSetup = new javax.swing.JPanel();
        btnAddPlayer = new javax.swing.JToggleButton();
        btnStartGame = new javax.swing.JButton();
        txtFplayername = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tokenList = new javax.swing.JList<>();
        nPlayers = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        playerList = new javax.swing.JList<>();
        startScreen = new javax.swing.JPanel();
        startFullGame = new javax.swing.JButton();
        startAbridgedGame = new javax.swing.JButton();
        txtGameLength = new javax.swing.JTextField();
        gameScreen = new javax.swing.JPanel();
        btnRollDice = new javax.swing.JToggleButton();
        txtCurrPos = new javax.swing.JLabel();
        txtRollValue = new javax.swing.JLabel();
        txtCurrPlayer = new javax.swing.JLabel();
        txtPlrBalance = new javax.swing.JLabel();
        btnNextPlayer = new javax.swing.JToggleButton();
        tmrTime = new javax.swing.JLabel();
        txtAvaliable = new javax.swing.JLabel();
        btnBuyProp = new javax.swing.JToggleButton();
        txtBankBalance = new javax.swing.JLabel();
        txtPrpCost = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        exitMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentsMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        buyDialog.setAlwaysOnTop(true);
        buyDialog.setMinimumSize(new java.awt.Dimension(100, 100));

        jLabel4.setText("Buy this property?");

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnBuy.setText("Buy");
        btnBuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuyActionPerformed(evt);
            }
        });

        txtName.setText("jLabel5");

        txtPrice.setText("jLabel6");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel4)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btnBack)
                            .addGap(67, 67, 67)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(txtName)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPrice))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(97, 97, 97)
                            .addComponent(btnBuy))))
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName)
                    .addComponent(txtPrice))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnBuy))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout buyDialogLayout = new javax.swing.GroupLayout(buyDialog.getContentPane());
        buyDialog.getContentPane().setLayout(buyDialogLayout);
        buyDialogLayout.setHorizontalGroup(
            buyDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        buyDialogLayout.setVerticalGroup(
            buyDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Property Tycoon Game");

        btnAddPlayer.setText("Add Player");
        btnAddPlayer.setFocusable(false);
        btnAddPlayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPlayerActionPerformed(evt);
            }
        });

        btnStartGame.setText("Start Game");
        btnStartGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartGameActionPerformed(evt);
            }
        });

        tokenList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tokenList.setVerifyInputWhenFocusTarget(false);
        tokenList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                tokenListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(tokenList);

        nPlayers.setText("Number of Players: ");

        jLabel1.setText("Name:");

        jLabel2.setText("Token:");

        jLabel3.setText("Players in current game:");

        playerList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(playerList);

        javax.swing.GroupLayout playerSetupLayout = new javax.swing.GroupLayout(playerSetup);
        playerSetup.setLayout(playerSetupLayout);
        playerSetupLayout.setHorizontalGroup(
            playerSetupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(playerSetupLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(playerSetupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(playerSetupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nPlayers)
                    .addGroup(playerSetupLayout.createSequentialGroup()
                        .addGroup(playerSetupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAddPlayer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtFplayername, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(playerSetupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnStartGame))))
                .addContainerGap(142, Short.MAX_VALUE))
        );
        playerSetupLayout.setVerticalGroup(
            playerSetupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(playerSetupLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(playerSetupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFplayername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(playerSetupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(playerSetupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddPlayer)
                    .addComponent(btnStartGame))
                .addGap(20, 20, 20)
                .addComponent(nPlayers)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        startFullGame.setText("Full Game");
        startFullGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startFullGameActionPerformed(evt);
            }
        });

        startAbridgedGame.setText("Abridged");
        startAbridgedGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startAbridgedGameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout startScreenLayout = new javax.swing.GroupLayout(startScreen);
        startScreen.setLayout(startScreenLayout);
        startScreenLayout.setHorizontalGroup(
            startScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(startScreenLayout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addGroup(startScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(startScreenLayout.createSequentialGroup()
                        .addComponent(startAbridgedGame)
                        .addGap(18, 18, 18)
                        .addComponent(txtGameLength, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(startFullGame))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        startScreenLayout.setVerticalGroup(
            startScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(startScreenLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(startFullGame)
                .addGap(18, 18, 18)
                .addGroup(startScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startAbridgedGame)
                    .addComponent(txtGameLength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(107, Short.MAX_VALUE))
        );

        btnRollDice.setText("Roll Dice");
        btnRollDice.setToolTipText("");
        btnRollDice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRollDiceActionPerformed(evt);
            }
        });

        txtCurrPos.setText("Current Position:");

        txtRollValue.setText("Roll Value:");

        txtCurrPlayer.setText("Player:");

        txtPlrBalance.setText("Balance:");

        btnNextPlayer.setText("Next Player");
        btnNextPlayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextPlayerActionPerformed(evt);
            }
        });

        txtAvaliable.setText("Avaliable: ");

        btnBuyProp.setText("Buy Property");
        btnBuyProp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuyPropActionPerformed(evt);
            }
        });

        txtBankBalance.setText("Bank Balance");

        txtPrpCost.setText("Cost:");

        javax.swing.GroupLayout gameScreenLayout = new javax.swing.GroupLayout(gameScreen);
        gameScreen.setLayout(gameScreenLayout);
        gameScreenLayout.setHorizontalGroup(
            gameScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gameScreenLayout.createSequentialGroup()
                .addGroup(gameScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gameScreenLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(gameScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnNextPlayer)
                            .addComponent(txtCurrPlayer)
                            .addGroup(gameScreenLayout.createSequentialGroup()
                                .addGroup(gameScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCurrPos)
                                    .addComponent(btnRollDice)
                                    .addComponent(txtAvaliable))
                                .addGap(36, 36, 36)
                                .addGroup(gameScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(gameScreenLayout.createSequentialGroup()
                                        .addComponent(txtPrpCost)
                                        .addGap(86, 86, 86)
                                        .addComponent(btnBuyProp))
                                    .addComponent(txtRollValue)
                                    .addGroup(gameScreenLayout.createSequentialGroup()
                                        .addComponent(txtPlrBalance)
                                        .addGap(136, 136, 136)
                                        .addComponent(txtBankBalance))))))
                    .addGroup(gameScreenLayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(tmrTime)))
                .addContainerGap(191, Short.MAX_VALUE))
        );
        gameScreenLayout.setVerticalGroup(
            gameScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gameScreenLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(tmrTime)
                .addGap(18, 18, 18)
                .addComponent(btnNextPlayer)
                .addGap(18, 18, 18)
                .addGroup(gameScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCurrPlayer)
                    .addComponent(txtPlrBalance)
                    .addComponent(txtBankBalance))
                .addGap(18, 18, 18)
                .addGroup(gameScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRollDice)
                    .addComponent(txtRollValue))
                .addGap(40, 40, 40)
                .addComponent(txtCurrPos)
                .addGap(18, 18, 18)
                .addGroup(gameScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAvaliable)
                    .addComponent(btnBuyProp)
                    .addComponent(txtPrpCost))
                .addGap(31, 31, 31))
        );

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentsMenuItem.setMnemonic('c');
        contentsMenuItem.setText("Contents");
        helpMenu.add(contentsMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(startScreen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(gameScreen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(playerSetup, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(startScreen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(gameScreen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(playerSetup, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void startFullGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startFullGameActionPerformed
        game = new CentralControl(0);
        fullGame = true;
        gui.startScreen.setVisible(false);
        gui.playerSetup.setVisible(true);
    }//GEN-LAST:event_startFullGameActionPerformed

    private void btnRollDiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRollDiceActionPerformed
        if (game.dices.rollAgain) {
            game.dices.rollDice();
            game.getCurrentPlayer().setLocation(game.getCurrentPlayer().getLocation() + game.dices.totalVal);
            if (game.dices.goJail) {
                game.getCurrentPlayer().setLocation(11);
            }
            //updateGUI();
        }
    }//GEN-LAST:event_btnRollDiceActionPerformed

    private void btnStartGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartGameActionPerformed
        Thread updGUI = new Thread(new Runnable() {
            @Override
            public void run() {
                new JFXPanel();
                Runnable upd = new Runnable() {
                    @Override
                    public void run() {
                        updateGUI();
                    }
                };
                while (true) {
                    try {
                        Thread.sleep(100);
                    } catch (InterruptedException ex) {
                    }

                    Platform.runLater(upd);
                }
            }

        });
        updGUI.setDaemon(true);
        updGUI.start();
        gui.playerSetup.setVisible(false);
        gui.gameScreen.setVisible(true);
        
    }//GEN-LAST:event_btnStartGameActionPerformed

    private void btnAddPlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPlayerActionPerformed
        Player p = new Player(txtFplayername.getText(), st);
        game.addPlayer(p);
        gui.nPlayers.setText("Number of Players: " + game.getPlayers().size());
        createPlayerList();

    }//GEN-LAST:event_btnAddPlayerActionPerformed

    private void tokenListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_tokenListValueChanged
        st = tokenList.getSelectedValue();
    }//GEN-LAST:event_tokenListValueChanged

    private void startAbridgedGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startAbridgedGameActionPerformed
        game = new CentralControl(90);
        gui.startScreen.setVisible(false);
        gui.playerSetup.setVisible(true);

        //running = true;
        //tmr();
    }//GEN-LAST:event_startAbridgedGameActionPerformed

    private void btnNextPlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextPlayerActionPerformed
        game.nextPlayer();
        game.dices.newPlayer();
        //updateGUI();
    }//GEN-LAST:event_btnNextPlayerActionPerformed

    private void btnBuyPropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuyPropActionPerformed
        Player p = game.getCurrentPlayer();
        gui.txtName.setText(((Property) game.board.getCell(p.getLocation())).getName());
        gui.txtPrice.setText(Integer.toString(((Property) game.board.getCell(p.getLocation())).getCost()));
        gui.buyDialog.setVisible(true);
        
        p.buyProperty((Property) game.board.getCell(p.getLocation()));
    }//GEN-LAST:event_btnBuyPropActionPerformed

    private void btnBuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuyActionPerformed
        game.getCurrentPlayer().buyProperty((Property) game.board.getCell(game.getCurrentPlayer().getLocation()));
        gui.buyDialog.setVisible(false);
    }//GEN-LAST:event_btnBuyActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        gui.buyDialog.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    private void updateGUI() {
        try{
            Player p = game.getCurrentPlayer();
        txtPlrBalance.setText("Balance: " + p.getMoney());
        txtRollValue.setText("Roll Value: " + game.dices.totalVal);
        txtCurrPlayer.setText("Player: " + p.getName());
        txtCurrPos.setText("Current Position: " + ((Property) game.board.getCell(p.getLocation())).getName());
        tmrTime.setText(game.getRemainingTime().toString());
        txtAvaliable.setText(Boolean.toString(((Property) game.board.getCell(p.getLocation())).isAvailable()));    //Waiting for board class.
        txtBankBalance.setText(Integer.toString(game.bank.getBalance()));
        txtPrpCost.setText(Integer.toString(((Property) game.board.getCell(p.getLocation())).getCost())); //Waiting for board class.
        }catch(NullPointerException ex){
            
        }
    }

    private void createTokenList() {
        tokenList.setModel(new javax.swing.AbstractListModel<Token>() {
            Token[] ts = Token.values();

            @Override
            public int getSize() {
                return ts.length;
            }

            @Override
            public Token getElementAt(int index) {
                return ts[index];
            }

        });

    }

    private void createPlayerList() {
        ArrayList<String> pn = new ArrayList<>();
        for (Player p : game.getPlayers()) {
            pn.add(p.getName());
        }

        playerList.setModel(new javax.swing.AbstractListModel<String>() {

            @Override
            public int getSize() {
                return pn.size();
            }

            @Override
            public String getElementAt(int index) {
                return pn.get(index);
            }

        });

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Mac OS X look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Mac OS X".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                gui = new GameGUI();
                gui.setVisible(true);
                gui.startScreen.setVisible(true);
                gui.gameScreen.setVisible(false);
                gui.playerSetup.setVisible(false);
                

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JToggleButton btnAddPlayer;
    private javax.swing.JToggleButton btnBack;
    private javax.swing.JToggleButton btnBuy;
    private javax.swing.JToggleButton btnBuyProp;
    private javax.swing.JToggleButton btnNextPlayer;
    private javax.swing.JToggleButton btnRollDice;
    private javax.swing.JButton btnStartGame;
    private javax.swing.JDialog buyDialog;
    private javax.swing.JMenuItem contentsMenuItem;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JPanel gameScreen;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JLabel nPlayers;
    private javax.swing.JList<String> playerList;
    private javax.swing.JPanel playerSetup;
    private javax.swing.JButton startAbridgedGame;
    private javax.swing.JButton startFullGame;
    private javax.swing.JPanel startScreen;
    private javax.swing.JLabel tmrTime;
    private javax.swing.JList<Token> tokenList;
    private javax.swing.JLabel txtAvaliable;
    private javax.swing.JLabel txtBankBalance;
    private javax.swing.JLabel txtCurrPlayer;
    private javax.swing.JLabel txtCurrPos;
    private javax.swing.JTextField txtFplayername;
    private javax.swing.JTextField txtGameLength;
    private javax.swing.JLabel txtName;
    private javax.swing.JLabel txtPlrBalance;
    private javax.swing.JLabel txtPrice;
    private javax.swing.JLabel txtPrpCost;
    private javax.swing.JLabel txtRollValue;
    // End of variables declaration//GEN-END:variables

}
