/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package propertytycoongame;

import propertytycoongame.Player.Token;

/**
 *
 * @author Hayden
 */
public class GameGUI extends javax.swing.JFrame {
    
    CentralControl game;
    static GameGUI gui;
    Dice dice = new Dice();
    Token st;
    Boolean fullGame;
    Boolean running = false;
    
    
    
    /**
     * Creates new form GameGUI
     */
    public GameGUI() {
        initComponents();
        createTokenList();
    }

    /**
     * This method is called from within the constructor to initialise the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        playerSetup = new javax.swing.JPanel();
        btnAddPlayer = new javax.swing.JToggleButton();
        btnStartGame = new javax.swing.JButton();
        txtFplayername = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tokenList = new javax.swing.JList<>();
        nPlayers = new javax.swing.JLabel();
        startScreen = new javax.swing.JPanel();
        startFullGame = new javax.swing.JButton();
        startAbridgedGame = new javax.swing.JButton();
        txtGameLength = new javax.swing.JTextField();
        gameScreen = new javax.swing.JPanel();
        btnRollDice = new javax.swing.JToggleButton();
        txtCurrPos = new javax.swing.JLabel();
        txtRollValue = new javax.swing.JLabel();
        txtCurrPlayer = new javax.swing.JLabel();
        txtPlrBalance = new javax.swing.JLabel();
        btnNextPlayer = new javax.swing.JToggleButton();
        tmrTime = new javax.swing.JLabel();
        txtAvaliable = new javax.swing.JLabel();
        btnBuyProp = new javax.swing.JToggleButton();
        txtBankBalance = new javax.swing.JLabel();
        txtPrpCost = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        exitMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentsMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Property Tycoon Game");

        btnAddPlayer.setText("Add Player");
        btnAddPlayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPlayerActionPerformed(evt);
            }
        });

        btnStartGame.setText("Start Game");
        btnStartGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartGameActionPerformed(evt);
            }
        });

        txtFplayername.setText("Player Name");

        tokenList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tokenList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                tokenListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(tokenList);

        nPlayers.setText("Number of Players: ");

        javax.swing.GroupLayout playerSetupLayout = new javax.swing.GroupLayout(playerSetup);
        playerSetup.setLayout(playerSetupLayout);
        playerSetupLayout.setHorizontalGroup(
            playerSetupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(playerSetupLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(playerSetupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(playerSetupLayout.createSequentialGroup()
                        .addComponent(nPlayers)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(playerSetupLayout.createSequentialGroup()
                        .addGroup(playerSetupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFplayername, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1)
                            .addComponent(btnAddPlayer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnStartGame)
                        .addGap(29, 29, 29))))
        );
        playerSetupLayout.setVerticalGroup(
            playerSetupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(playerSetupLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(txtFplayername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(playerSetupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnStartGame)
                    .addComponent(btnAddPlayer))
                .addGap(18, 18, 18)
                .addComponent(nPlayers)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        startFullGame.setText("Full Game");
        startFullGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startFullGameActionPerformed(evt);
            }
        });

        startAbridgedGame.setText("Abridged");
        startAbridgedGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startAbridgedGameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout startScreenLayout = new javax.swing.GroupLayout(startScreen);
        startScreen.setLayout(startScreenLayout);
        startScreenLayout.setHorizontalGroup(
            startScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(startScreenLayout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addGroup(startScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(startScreenLayout.createSequentialGroup()
                        .addComponent(startAbridgedGame)
                        .addGap(18, 18, 18)
                        .addComponent(txtGameLength, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(startFullGame))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        startScreenLayout.setVerticalGroup(
            startScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(startScreenLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(startFullGame)
                .addGap(18, 18, 18)
                .addGroup(startScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startAbridgedGame)
                    .addComponent(txtGameLength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(107, Short.MAX_VALUE))
        );

        btnRollDice.setText("Roll Dice");
        btnRollDice.setToolTipText("");
        btnRollDice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRollDiceActionPerformed(evt);
            }
        });

        txtCurrPos.setText("Current Position:");

        txtRollValue.setText("Roll Value:");

        txtCurrPlayer.setText("Player:");

        txtPlrBalance.setText("Balance:");

        btnNextPlayer.setText("Next Player");
        btnNextPlayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextPlayerActionPerformed(evt);
            }
        });

        txtAvaliable.setText("Avaliable: ");

        btnBuyProp.setText("Buy Property");
        btnBuyProp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuyPropActionPerformed(evt);
            }
        });

        txtBankBalance.setText("Bank Balance");

        txtPrpCost.setText("Cost:");

        javax.swing.GroupLayout gameScreenLayout = new javax.swing.GroupLayout(gameScreen);
        gameScreen.setLayout(gameScreenLayout);
        gameScreenLayout.setHorizontalGroup(
            gameScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gameScreenLayout.createSequentialGroup()
                .addGroup(gameScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gameScreenLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(gameScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnNextPlayer)
                            .addComponent(txtCurrPlayer)
                            .addGroup(gameScreenLayout.createSequentialGroup()
                                .addGroup(gameScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCurrPos)
                                    .addComponent(btnRollDice)
                                    .addComponent(txtAvaliable))
                                .addGap(36, 36, 36)
                                .addGroup(gameScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(gameScreenLayout.createSequentialGroup()
                                        .addComponent(txtPrpCost)
                                        .addGap(86, 86, 86)
                                        .addComponent(btnBuyProp))
                                    .addComponent(txtRollValue)
                                    .addGroup(gameScreenLayout.createSequentialGroup()
                                        .addComponent(txtPlrBalance)
                                        .addGap(136, 136, 136)
                                        .addComponent(txtBankBalance))))))
                    .addGroup(gameScreenLayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(tmrTime)))
                .addContainerGap(191, Short.MAX_VALUE))
        );
        gameScreenLayout.setVerticalGroup(
            gameScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gameScreenLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(tmrTime)
                .addGap(18, 18, 18)
                .addComponent(btnNextPlayer)
                .addGap(18, 18, 18)
                .addGroup(gameScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCurrPlayer)
                    .addComponent(txtPlrBalance)
                    .addComponent(txtBankBalance))
                .addGap(18, 18, 18)
                .addGroup(gameScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRollDice)
                    .addComponent(txtRollValue))
                .addGap(40, 40, 40)
                .addComponent(txtCurrPos)
                .addGap(18, 18, 18)
                .addGroup(gameScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAvaliable)
                    .addComponent(btnBuyProp)
                    .addComponent(txtPrpCost))
                .addGap(31, 31, 31))
        );

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentsMenuItem.setMnemonic('c');
        contentsMenuItem.setText("Contents");
        helpMenu.add(contentsMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(startScreen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(gameScreen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(playerSetup, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(startScreen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(gameScreen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(playerSetup, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void startFullGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startFullGameActionPerformed
        game = new CentralControl(0);
        fullGame = true;
        gui.startScreen.setVisible(false);
        gui.playerSetup.setVisible(true);
    }//GEN-LAST:event_startFullGameActionPerformed

    private void btnRollDiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRollDiceActionPerformed
        if(dice.rollAgain){
            dice.rollDice();
            game.getCurrentPlayer().setLocation(game.getCurrentPlayer().getLocation() + dice.totalVal);
            if(dice.goJail){
                game.getCurrentPlayer().setLocation(11);
            }
            updateGUI();
        }
    }//GEN-LAST:event_btnRollDiceActionPerformed

    private void btnStartGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartGameActionPerformed
        gui.playerSetup.setVisible(false);
        gui.gameScreen.setVisible(true);
        updateGUI();
    }//GEN-LAST:event_btnStartGameActionPerformed

    private void btnAddPlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPlayerActionPerformed
        Player p = new Player(txtFplayername.getText(), st);
        game.addPlayer(p);
        gui.nPlayers.setText("Number of Players: " + game.getPlayers().size());
    }//GEN-LAST:event_btnAddPlayerActionPerformed

    private void tokenListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_tokenListValueChanged
        st = tokenList.getSelectedValue();
    }//GEN-LAST:event_tokenListValueChanged

    private void startAbridgedGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startAbridgedGameActionPerformed
        game = new CentralControl(90);
        gui.startScreen.setVisible(false);
        gui.playerSetup.setVisible(true);
        
        //running = true;
        //tmr();
    }//GEN-LAST:event_startAbridgedGameActionPerformed

    private void btnNextPlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextPlayerActionPerformed
        game.nextPlayer();
        dice.newPlayer();
        updateGUI();
    }//GEN-LAST:event_btnNextPlayerActionPerformed

    private void btnBuyPropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuyPropActionPerformed
        
    }//GEN-LAST:event_btnBuyPropActionPerformed

    private void updateGUI(){
        txtPlrBalance.setText("Balance: "+ game.getCurrentPlayer().getMoney());
        txtRollValue.setText("Roll Value: " + dice.totalVal);
        txtCurrPlayer.setText("Player:" + (game.getCurrentPlayer()).getName());
        txtCurrPos.setText("Current Position: " + game.getCurrentPlayer().getLocation());
        tmrTime.setText(game.getRemainingTime().toString());
        //txtAvaliable.setText(game.getCurrentPlayer().getLocation();    //Waiting for board class.
        txtBankBalance.setText(Integer.toString(game.bank.getBalance()));
        //txtPrpCost.setText(Integer.toString(game.getCurrentPlayer().getLocation())); //Waiting for board class.
        
    }
    
//    private void tmr(){
//        while(running){
//            gui.tmrTime.setText(game.getRemainingTime().toString());
//        }
//    }
    
    
    private void createTokenList(){
        tokenList.setModel(new javax.swing.AbstractListModel<Token>() {
            Token[] ts = Token.values();
            @Override
            public int getSize() {
                return ts.length;
            }
            @Override
            public Token getElementAt(int index) {
                return ts[index];
            }
            
        });
        //Token[] ts = Token.values();
        
        
//        tokenList.setModel(new javax.swing.AbstractListModel<Token>() {
//            String[] strings = { "token1", "token2" };
//            public int getSize() { return strings.length; }
//            public Object getElementAt(int i) { return strings[i]; }
//        });
       
    }
   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        /* Set the Mac OS X look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Mac OS X".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                
                gui = new GameGUI();
                gui.setVisible(true);
                gui.startScreen.setVisible(true);
                gui.gameScreen.setVisible(false);
                gui.playerSetup.setVisible(false);
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JToggleButton btnAddPlayer;
    private javax.swing.JToggleButton btnBuyProp;
    private javax.swing.JToggleButton btnNextPlayer;
    private javax.swing.JToggleButton btnRollDice;
    private javax.swing.JButton btnStartGame;
    private javax.swing.JMenuItem contentsMenuItem;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JPanel gameScreen;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JLabel nPlayers;
    private javax.swing.JPanel playerSetup;
    private javax.swing.JButton startAbridgedGame;
    private javax.swing.JButton startFullGame;
    private javax.swing.JPanel startScreen;
    private javax.swing.JLabel tmrTime;
    private javax.swing.JList<Token> tokenList;
    private javax.swing.JLabel txtAvaliable;
    private javax.swing.JLabel txtBankBalance;
    private javax.swing.JLabel txtCurrPlayer;
    private javax.swing.JLabel txtCurrPos;
    private javax.swing.JTextField txtFplayername;
    private javax.swing.JTextField txtGameLength;
    private javax.swing.JLabel txtPlrBalance;
    private javax.swing.JLabel txtPrpCost;
    private javax.swing.JLabel txtRollValue;
    // End of variables declaration//GEN-END:variables

}
